name: 'Test Build'

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install frontend dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Build Tauri app
        run: npm run tauri:build

      - name: List build outputs
        shell: bash
        run: |
          echo "Listing target/release contents:" && ls -la src-tauri/target/release || true
          echo "Listing bundle contents recursively:" && ls -laR src-tauri/target/release/bundle || true

      - name: Upload artifacts (bundle and executables)
        uses: actions/upload-artifact@v4
        with:
          name: xmail-${{ matrix.platform }}-bundle
          path: |
            src-tauri/target/release/bundle/**
            src-tauri/target/release/*.exe
          if-no-files-found: warn
          retention-days: 10